# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Side Scroll Jekyll Theme
email: rdedwardes@digitalroots.io
description: Jekyll Blog Theme useing only CSS and HTML
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://digitalroots.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
logo: logo-no-text.png
# Build settings
markdown: kramdown
permalink: :title
